use_frameworks!

target 'HMCDownloadManager_Example' do
  pod 'HMCDownloadManager', :path => '../'

  target 'HMCDownloadManager_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
